### ISSUE TITLE
taglib-ruby has warnings with Ruby 2.7.0 preview3 (waiting for swig release)

### ISSUE THREAD

**Issue by jeremyevans** [robinst/taglib-ruby#85]
I originally thought this could be a bug in Ruby itself, but according to my fellow ruby committer @shyouhei, this is due to problems in SWIG.

Here is an example error message when compiling (there are many like this):

```
taglib_base_wrap.cxx:2101:9: error: no matching function for call to 'rb_rescue'
    if (rb_rescue(RUBY_METHOD_FUNC(SWIG_AUX_NUM2ULONG), (VALUE)a, RUBY_METHOD_FUNC(SWIG_ruby_failed), 0) != Qnil) {                                                                                               
             ^~~~~~~~~                                       
                                                                                                                                                      
    /usr/local/include/ruby-2.7/ruby/ruby.h:1989:7: note: candidate function not viable: no known conversion from 'VALUE (VALUE *)' (aka 'unsigned long (unsigned long *)') to 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)') for 1st argument                                                                                                                                                               
    VALUE rb_rescue(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE);
```

Here are @shyouhei's comments:

```
Well, it seems the function called SWIG_ruby_failed is
prototyped as VALUE SWIG_ruby_failed(void) (source:
https://github.com/swig/swig/blob/master/Lib/ruby/rubyprimtypes.swg).

However the third argument of rb_rescue() is
VALUE (*)(VALUE, VALUE) (source: ruby.h).

So yes, the API change revealed an arity mismatch here. SWIG_ruby_failed
is getting more arguments than it expects, which is dangerous depending
on machine ABI. It has to be fixed. I believe it's SWIG, not the gem, wihch
has to handle this.
```

See https://bugs.ruby-lang.org/issues/16271 for my initial bug report to Ruby.

I don't think you can fix this without an update to SWIG, so you'll probably need to report this upstream to SWIG.  After SWIG fixes it, I'm guessing you'll need to regenerate the `cxx` files from the `i` files with an updated SWIG version (I don't have any experience with SWIG).

**Comment by robinst** [comment]
Hey, thanks for reporting. So, sounds like `SWIG_ruby_failed` needs to get a second argument?:

https://github.com/swig/swig/blob/master/Lib/ruby/rubyprimtypes.swg#L13

I'm also not sure why it's `void` instead of `VALUE`. Can you try to see if changing `rubyprimtypes.swg` in your local swig installation to this fixes it?:

```
%fragment("SWIG_ruby_failed","header")
{
SWIGINTERN VALUE
SWIG_ruby_failed(VALUE, VALUE)
{
  return Qnil;
} 
}
```

**Comment by jeremyevans** [comment]
That looks like it will fix it.  I believe another ruby committer, @n0kada, added some backwards compatibility to Ruby 2.7 (after preview2) so taglib-ruby should continue to work in ruby 2.7.0.  However, this is still something that should be fixed long-term.

I don't have a local swig installation, I'm using the already generated cxx files for compiling.  However, if there are instructions for updating the cxx files from the i files using swig, please point me to them and I'll get swig installed and do some testing.

**Comment by Sigill** [comment]
https://github.com/robinst/taglib-ruby#building

**Comment by robinst** [comment]
@Sigill's link is if you want to regenerate the wrappers.

But I also just pushed a `issue-85-try-change-generated-code` branch with the changes to the wrappers directly, can you try that?: https://github.com/robinst/taglib-ruby/tree/issue-85-try-change-generated-code

**Comment by regismesquita** [comment]
@robinst I've tried using your branch but I am still facing the issue reported by @jeremyevans .

```
current directory: /Users/rdsm/.rvm/gems/ruby-2.7.0-preview2/bundler/gems/taglib-ruby-77254b68a361/ext/taglib_base
make "DESTDIR="
compiling taglib_base_wrap.cxx
In file included from taglib_base_wrap.cxx:1873:
In file included from /usr/local/include/taglib/tlist.h:263:
In file included from /usr/local/include/taglib/tlist.tcc:27:
/usr/local/include/taglib/trefcounter.h:83:18: warning: 'OSAtomicIncrement32Barrier' is deprecated: first deprecated in macOS
10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
    void ref() { OSAtomicIncrement32Barrier(const_cast<int32_t*>(&refCount)); }
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:182:9: note:
'OSAtomicIncrement32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicIncrement32Barrier( volatile int32_t *__theValue );
        ^
In file included from taglib_base_wrap.cxx:1873:
In file included from /usr/local/include/taglib/tlist.h:263:
In file included from /usr/local/include/taglib/tlist.tcc:27:
/usr/local/include/taglib/trefcounter.h:84:29: warning: 'OSAtomicDecrement32Barrier' is deprecated: first deprecated in macOS
10.12 - Use std::atomic_fetch_sub() from <atomic> instead [-Wdeprecated-declarations]
    bool deref() { return ! OSAtomicDecrement32Barrier(const_cast<int32_t*>(&refCount)); }
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:201:9: note:
'OSAtomicDecrement32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicDecrement32Barrier( volatile int32_t *__theValue );
        ^
taglib_base_wrap.cxx:2101:9: error: no matching function for call to 'rb_rescue'
    if (rb_rescue(RUBY_METHOD_FUNC(SWIG_AUX_NUM2ULONG), (VALUE)a, RUBY_METHOD_FUNC(SWIG_ruby_failed), 0) != Qnil) {
        ^~~~~~~~~
/Users/rdsm/.rvm/rubies/ruby-2.7.0-preview2/include/ruby-2.7.0/ruby/ruby.h:1989:7: note: candidate function not viable: no
known conversion from 'VALUE (VALUE *)' (aka 'unsigned long (unsigned long *)') to 'VALUE (*)(VALUE)' (aka 'unsigned long
(*)(unsigned long)') for 1st argument
VALUE rb_rescue(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE);
      ^
/Users/rdsm/.rvm/rubies/ruby-2.7.0-preview2/include/ruby-2.7.0/ruby/backward/cxxanyargs.hpp:198:1: note: candidate function not
viable: no known conversion from 'VALUE (VALUE *)' (aka 'unsigned long (unsigned long *)') to 'ruby::backward::cxxanyargs::type
*' (aka 'unsigned long (*)(...)') for 1st argument
rb_rescue(type *q, VALUE w, type *e, VALUE r)
^
taglib_base_wrap.cxx:2153:9: error: no matching function for call to 'rb_rescue'
    if (rb_rescue(RUBY_METHOD_FUNC(SWIG_AUX_NUM2LONG), (VALUE)a, RUBY_METHOD_FUNC(SWIG_ruby_failed), 0) != Qnil) {
        ^~~~~~~~~
/Users/rdsm/.rvm/rubies/ruby-2.7.0-preview2/include/ruby-2.7.0/ruby/ruby.h:1989:7: note: candidate function not viable: no
known conversion from 'VALUE (VALUE *)' (aka 'unsigned long (unsigned long *)') to 'VALUE (*)(VALUE)' (aka 'unsigned long
(*)(unsigned long)') for 1st argument
VALUE rb_rescue(VALUE(*)(VALUE),VALUE,VALUE(*)(VALUE,VALUE),VALUE);
      ^
/Users/rdsm/.rvm/rubies/ruby-2.7.0-preview2/include/ruby-2.7.0/ruby/backward/cxxanyargs.hpp:198:1: note: candidate function not
viable: no known conversion from 'VALUE (VALUE *)' (aka 'unsigned long (unsigned long *)') to 'ruby::backward::cxxanyargs::type
*' (aka 'unsigned long (*)(...)') for 1st argument
rb_rescue(type *q, VALUE w, type *e, VALUE r)
^
2 warnings and 2 errors generated.
make: *** [taglib_base_wrap.o] Error 1

make failed, exit code 2
```

**Comment by jeremyevans** [comment]
Note that taglib builds correctly Ruby 2.7.0-preview3. What were previously errors in preview2 have been downgraded to warnings:

```
taglib_wav_wrap.cxx:2024:9: warning: 'rb_rescue' is deprecated: Use of ANYARGS in this function is deprected [-Wdeprecated-declarations]
    if (rb_rescue(RUBY_METHOD_FUNC(SWIG_AUX_NUM2LONG), (VALUE)a, RUBY_METHOD_FUNC(SWIG_ruby_failed), 0) != Qnil) {
        ^
/usr/local/include/ruby-2.7/ruby/backward/cxxanyargs.hpp:184:1: note: 'rb_rescue' has been explicitly marked deprecated here
RUBY_CXX_DEPRECATED("Use of ANYARGS in this function is deprected")
^
/usr/local/include/ruby-2.7/x86_64-openbsd/ruby/config.h:146:49: note: expanded from macro 'RUBY_CXX_DEPRECATED'
#define RUBY_CXX_DEPRECATED(msg) __attribute__((__deprecated__(msg)))
                                                ^
taglib_wav_wrap.cxx:2119:9: warning: 'rb_rescue' is deprecated: Use of ANYARGS in this function is deprected [-Wdeprecated-declarations]
    if (rb_rescue(RUBY_METHOD_FUNC(SWIG_AUX_NUM2ULONG), (VALUE)a, RUBY_METHOD_FUNC(SWIG_ruby_failed), 0) != Qnil) {
        ^
/usr/local/include/ruby-2.7/ruby/backward/cxxanyargs.hpp:184:1: note: 'rb_rescue' has been explicitly marked deprecated here
RUBY_CXX_DEPRECATED("Use of ANYARGS in this function is deprected")
^
/usr/local/include/ruby-2.7/x86_64-openbsd/ruby/config.h:146:49: note: expanded from macro 'RUBY_CXX_DEPRECATED'
#define RUBY_CXX_DEPRECATED(msg) __attribute__((__deprecated__(msg)))
```

**Comment by robinst** [comment]
There's a fix in swig now: https://github.com/swig/swig/issues/1689

I think with it only being a warning for now, we can wait for the next swig release and then regenerate the bindings.

**Comment by jeremyevans** [comment]
While not related to the previous issue, I found that taglib 1.1.0 issues a warning when loaded on Ruby 3.2.0-preview1:

```
/usr/local/lib/ruby/gems/3.2/gems/taglib-ruby-1.1.0/lib/taglib_base.so: warning: undefining the allocator of T_DATA class swig_runtime_data
```

No runtime warning when using Ruby 3.0 or 3.1. Ruby 3.2.0 won't be released until near the end of the year, so hopefully this can be addressed before then.  This also looks like an issue in swig and not specifically in taglib-ruby.

**Comment by robinst** [comment]
@jeremyevans Thanks, created a new issue here: https://github.com/robinst/taglib-ruby/issues/115

**Comment by robinst** [comment]
Alright, I've now merged PR #119 to regenerate wrappers with swig 4.0.2 which should fix the warnings.
